//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Registration_dbo
    {
        public int UserID { get; set; }

        [Required(ErrorMessage = "please Enter Uniquename", AllowEmptyStrings = false)]
        public string Uniquename { get; set; }
        [Required(ErrorMessage = "please Enter Last Name", AllowEmptyStrings = false)]
        public string Last_Name { get; set; }
        [Required(ErrorMessage = "please Enter Email", AllowEmptyStrings = false)]
        [RegularExpression("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$", ErrorMessage = "email id is Not in a correct format")]

        public string Email { get; set; }
        [Required(ErrorMessage = "please Enter Pass Word", AllowEmptyStrings = false)]
        public string Password { get; set; }
        [Required(ErrorMessage = "please Enter Mobile No", AllowEmptyStrings = false)]
        [StringLength(10, ErrorMessage = "minimum 10 digit", MinimumLength = 10)]
        public string MobileNo { get; set; }
    
        public virtual Login Login { get; set; }



    }
  
    }


